In [17]:
import numpy as np

In [4]:
x = 5

In [7]:
print ("X is {}".format(x))

X is 5


In [18]:
x = np.array([1,2,3,4])

In [21]:
print(np.linalg.norm(x))

5.477225575051661


In [25]:
print(np.linalg.norm([3,6,-6]))

9.0


In [19]:
print ("X is {}".format(x))

X is [1 2 3 4]


In [34]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2,2,1]])
z = a + b
print(z)


[[ 3  4  4]
 [ 6  7  7]
 [ 9 10 10]]


In [27]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
v = np.array([4,0,-1])
u = np.array([2,8,-2])
n = np.dot(v,u)
print(n)

10


In [36]:
A = np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
id = np.eye(4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
id = np.eye(5)
print(id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [42]:
id = np.eye(2)
print(id)
v = np.array([[1,2],[3,4]])
print(v)
z = id * v
print(z)

[[1. 0.]
 [0. 1.]]
[[1 2]
 [3 4]]
[[1. 0.]
 [0. 4.]]
